"""Render a candidate acquisition program with the 7 constants substituted.

The 7 constants are inline numeric literals inside ``_acquire`` /
``_dual_window_acquire``, not named parameters, so they cannot be overridden by
setting an attribute. Refactoring ``nvision/`` to extract them is out of the
question here (production carries unrelated uncommitted work), so this module
reuses the mechanism the neighbouring ``sbed_acquisition`` harness already
relies on: write a standalone module containing the three acquisition functions
and monkeypatch it onto the real locator class for the duration of one
evaluation.

The template is **derived at runtime** from
``openevolve/sbed_acquisition/initial_program.py`` rather than kept as a second
checked-in copy. A checked-in copy silently rots the moment production or the
evolve target changes a line, and the failure mode is the worst one available:
the optimizer keeps scoring an old acquisition function while reporting numbers
as if they came from the current one. Deriving it means there is exactly one
source of truth, and if any anchored literal stops matching -- because someone
edited that line -- :func:`render` raises instead of quietly substituting
nothing.

Substitution count is asserted per site. Each of the 8 edit sites (7 constants;
``jitter_hz`` appears twice, as the ``j_min``/``j_max`` pair) must match exactly
once.
"""

from __future__ import annotations

import difflib
import re
import tempfile
from pathlib import Path

from .space import BASELINE_PARAMS, repair_params

HARNESS_DIR = Path(__file__).resolve().parent.parent / "sbed_acquisition"
BASELINE_PROGRAM = HARNESS_DIR / "initial_program.py"

# (regex, replacement-template). Replacement templates use ``%`` formatting and
# are injected through a callable so that ``re`` never reinterprets backslashes
# or group references in the substituted text.
_SITES: tuple[tuple[str, str], ...] = (
    (
        r"decay = np\.exp\(-self\.inference_step_count / 25\.0\)",
        "decay = np.exp(-self.inference_step_count / %(decay_tau)r)",
    ),
    (
        r"if rand_val < 0\.1 \* decay:",
        "if rand_val < %(explore_p)r * decay:",
    ),
    (
        r"elif rand_val < 0\.2:",
        "elif rand_val < %(dip_p)r:",
    ),
    (
        r"if n_obs >= 5:",
        "if n_obs >= %(min_obs)d:",
    ),
    (
        r"j_min = max\(-5e6, orig_lo - center\)",
        "j_min = max(-%(jitter_hz)r, orig_lo - center)",
    ),
    (
        r"j_max = min\(5e6, orig_hi - center\)",
        "j_max = min(%(jitter_hz)r, orig_hi - center)",
    ),
    (
        r"if split_hat < 3\.0 \* lw_hat:",
        "if split_hat < %(dual_trigger)r * lw_hat:",
    ),
    # The ``0.9 * split_hat`` clamp is a hard runtime backstop against the two
    # flank windows overlapping (see space.py). The feasible set already
    # guarantees ``dual_halfwidth <= dual_trigger``, so at any point this
    # optimizer proposes the clamp is inactive and the rendered baseline behaves
    # exactly as production does.
    (
        r"half_width = 3\.0 \* lw_hat",
        "half_width = min(%(dual_halfwidth)r * lw_hat, 0.9 * split_hat)",
    ),
)

_HEADER = "# GENERATED by openevolve/sbed_constants/candidate.py -- do not edit by hand.\n"

# A substring uniquely identifying each of the 8 edit sites' source lines. Used
# by :func:`check_baseline_render` to prove the renderer touched these lines and
# nothing else.
_SITE_MARKERS: tuple[str, ...] = (
    "decay = np.exp",
    "if rand_val <",
    "elif rand_val <",
    "if n_obs >=",
    "j_min =",
    "j_max =",
    "if split_hat <",
    "half_width =",
)


def render(params: dict[str, float]) -> str:
    """Return the source of a candidate program with ``params`` substituted in."""
    repaired = repair_params(params)
    fields = {
        "decay_tau": float(repaired["decay_tau"]),
        "explore_p": float(repaired["explore_p"]),
        "dip_p": float(repaired["dip_p"]),
        "min_obs": int(repaired["min_obs"]),
        "jitter_hz": float(repaired["jitter_hz"]),
        "dual_trigger": float(repaired["dual_trigger"]),
        "dual_halfwidth": float(repaired["dual_halfwidth"]),
    }

    source = BASELINE_PROGRAM.read_text(encoding="utf-8")
    for pattern, template in _SITES:
        replacement = template % fields
        source, count = re.subn(pattern, lambda _m, r=replacement: r, source, count=1)
        if count != 1:
            raise RuntimeError(
                f"constant site {pattern!r} matched {count} times in {BASELINE_PROGRAM} (expected exactly 1). "
                "The acquisition source has changed -- re-anchor _SITES in candidate.py "
                "before trusting any result from this optimizer."
            )
    return _HEADER + source


def check_template() -> None:
    """Fail fast at startup if any anchored literal no longer matches its site.

    Rendering the *baseline* constants exercises all 8 sites, so a drifted
    source is reported before an optimization run spends an hour measuring a
    template that substituted nothing.
    """
    compile(render(BASELINE_PARAMS), "<sbed-constants-template-check>", "exec")


def baseline_render_diff() -> list[str]:
    """Changed lines between ``initial_program.py`` and its render at the defaults."""
    original = BASELINE_PROGRAM.read_text(encoding="utf-8").splitlines()
    rendered = render(BASELINE_PARAMS).splitlines()
    return [
        line
        for line in difflib.unified_diff(
            original, rendered, "initial_program.py", "rendered-defaults", n=0, lineterm=""
        )
        if line.startswith(("+", "-")) and not line.startswith(("+++", "---"))
    ]


def check_baseline_render() -> list[str]:
    """Structural proof that rendering the defaults reproduces the baseline.

    This is worth far more than observing that the two *score* similarly: at this
    evaluation noise two genuinely different acquisition functions score
    similarly all the time, so a score comparison cannot establish equivalence.

    Every changed line must be either the generated-file header or one of the 8
    known substitution sites. Some of those lines change textually without
    changing meaning -- ``5e6`` renders as ``5000000.0``, which is the same
    float -- so the check is "the renderer touched only the lines it is supposed
    to touch", not "the text is identical".

    At the defaults the only *semantic* change is ``half_width`` gaining its
    ``min(..., 0.9 * split_hat)`` non-overlap backstop, and that term cannot bind
    while ``dual_halfwidth <= dual_trigger`` (which the feasible set guarantees),
    so the rendered defaults execute the baseline algorithm.

    Returns the diff for display; raises if anything unexpected changed.
    """
    diff = baseline_render_diff()
    unexpected = [
        line for line in diff if "GENERATED by" not in line and not any(marker in line for marker in _SITE_MARKERS)
    ]
    if unexpected:
        raise RuntimeError(
            "rendering the default constants changed lines outside the 8 known substitution sites:\n"
            + "\n".join(unexpected)
            + "\nThe renderer is not reproducing the baseline algorithm -- fix it before optimizing, "
            "because every result would be measured against the wrong control."
        )
    return diff


def write_candidate(params: dict[str, float], directory: str | Path | None = None) -> Path:
    """Write a rendered candidate to a ``.py`` file and return its path."""
    target = Path(directory) if directory is not None else Path(tempfile.gettempdir())
    target.mkdir(parents=True, exist_ok=True)
    fd, name = tempfile.mkstemp(prefix="sbed_const_", suffix=".py", dir=str(target))
    with open(fd, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(render(params))
    return Path(name)
